### PR TITLE
Add note about govendor

### PR DESCRIPTION
**Pull request by porty**
I had to ask to work out what vendoring/dependency tool was being used. Hopefully the next person won't have to 😎.

I'm not married to the term _ dependency_, I'm never sure to use that or _vendoring_ in Go.

I figured the developer can follow the link to work out usage as anything written here wouldn't be as good.

### CODE REVIEW

**Comment by lox** [comment]
Thanks @porty, this is the wording we go with for buildkite/agent: https://github.com/buildkite/agent#dependency-management

**Comment by lox** [comment]
I kind of like "Dependendies"

**Comment by porty** [comment]
Ah geez, this is _after_ fixing up some spelling 😕- will fix

**Comment by lox** [comment]
All good, story of my liffe!

**Comment by lox** [comment]
Many thanks, sorry it was unclear to begin with!

**Pull request merged**
